# Generated by Django 5.0.7 on 2024-08-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_alter_book_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('appearance', models.TextField()),
                ('locations', models.TextField()),
                ('associates', models.TextField()),
                ('position', models.TextField()),
                ('knowledge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='books.book', verbose_name='book')),
            ],
        ),
    ]
