# Generated by Django 5.0.7 on 2024-12-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_user'),
        ('characters', '0002_alter_character_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='book',
        ),
        migrations.AddField(
            model_name='character',
            name='books',
            field=models.ManyToManyField(related_name='characters', to='books.book', verbose_name='book'),
        ),
    ]
