# Generated by Django 5.0.7 on 2024-07-24 23:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="book",
            managers=[
                ("books", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
